name: BuiKern S9Ta9

on:
  workflow_dispatch:

jobs:
  build:
    name: BuiKern S9Ta9 by ${{ github.actor }}
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      SUBARCH: arm64

      WORKSPACE: ${{ github.workspace }}/kernel_workspace
      KERNEL_DIR: ${{ github.workspace }}/kernel_workspace/gta9
      OUT_DIR: ${{ github.workspace }}/kernel_workspace/gta9/out

      KERNEL_REPO: https://github.com/prabhatkrmishra/kernel_samsung_gta9.git
      KERNEL_BRANCH: "15.0"
      DEFCONFIG: "gta9_defconfig"

      CLANG_VERSION: r416183b
      SUSFS_BRANCH: gki-android13-5.10

      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
```
